server:
  tomcat:
    uri-encoding: UTF-8
  port: 9998

spring:
    datasource:
        name: oracloud
        url: jdbc:mysql://stage-audio.oradt.com/wallet_common?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: Oradt!123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 10
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

rpc:
    bch:
        url: "http://ELB-TCP-Blockchain-8ce9078d9f50e341.elb.cn-northwest-1.amazonaws.com.cn:8432/"
        username: "ora"
        password: "Oradt!1234"
    doge:
        url: "http://ELB-TCP-Blockchain-8ce9078d9f50e341.elb.cn-northwest-1.amazonaws.com.cn:22555/"
        username: "ora"
        password: "Oradt!1234"
    btg:
        url: "http://ELB-TCP-Blockchain-8ce9078d9f50e341.elb.cn-northwest-1.amazonaws.com.cn:9050/"
        username: "ora"
        password: "Oradt!1234"
    dark:
        url: "http://ELB-TCP-Blockchain-8ce9078d9f50e341.elb.cn-northwest-1.amazonaws.com.cn:9998/"
        username: "ora"
        password: "Oradt!1234"
    ltc:
        url: "http://ELB-TCP-Blockchain-8ce9078d9f50e341.elb.cn-northwest-1.amazonaws.com.cn:9332/"
        username: "ora"
        password: "Oradt!1234"
    btc:
        url: "http://ELB-Blockchain-1732218811.cn-northwest-1.elb.amazonaws.com.cn:8332"
        username: "ora"
        password: "Oradt!1234"
    web3j:
        eth: "http://107.150.99.155:8545"
        etc: "http://52.83.130.131:8545"